name: combination of status check func and continue on error
on: push
jobs:
  combination:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - run: echo "when failure"
        if: ${{ failure() }}
      - run: echo "when success"
        if: ${{ success() }}
